#!/bin/bash

# Find JDK 17 in a common location
for jdk_path in \
  /usr/lib/jvm/java-17-openjdk* \
  /usr/lib/jvm/jdk-17* \
  /Library/Java/JavaVirtualMachines/jdk-17*.jdk/Contents/Home \
  /Library/Java/JavaVirtualMachines/temurin-17*.jdk/Contents/Home \
  /Library/Java/JavaVirtualMachines/openjdk-17*.jdk/Contents/Home \
  "$HOME/.sdkman/candidates/java/"*17*
do
  if [ -d "$jdk_path" ]; then
    echo "Using JDK at: $jdk_path"
    JAVA_HOME="$jdk_path" ./gradlew "$@"
    exit $?
  fi
done

echo "Error: Could not find JDK 17 in any standard location. Please install JDK 17."
exit 1 